language: php
sudo: false
dist: trusty
php:
  - 7.1
  - 7.2
  - nightly
before_install:
  - travis_retry composer self-update
  - travis_retry composer update --no-interaction --prefer-source
cache:
  directories:
    - $HOME/.composer/cache
